* sigscheme/syntax.c   - (scm_s_do): Fix incorrect syntax application for scm_s_begin()     which uses eval_state invalidly, with FOR_EACH_PAIR() * sigscheme/test/test-exp.scm   - Add various tests for 'do'. Some tests cause error
    $ ./sscm test/test-exp.scm
    error: no error has occurred in test do invalid form: non-list bindings form #2
    error: no error has occurred in test do invalid form: duplicate variable name #1
    error: no error has occurred in test do invalid form: duplicate variable name #2
    error: no error has occurred in test do invalid form: improper binding #3
    error: no error has occurred in test do invalid form: improper commands #1
    error: do valid form: no exps #1
     expected: <#<undef>>
       actual: <#t>
    FAILED: 1 tests, 272 assertions, 266 successes, 6 failures, 0 errors

    And "do invalid form: non-list test form" causes SEGV