missing includes for libnotify
In file included from uim-libnotify.c:33:
../uim/config.h:719:10: fatal error: os_dep.h: No such file or directory
  719 | #include "os_dep.h"
          |          ^~~~~~~~~~

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>